### ISSUE TITLE
Nothing will be logged

### ISSUE THREAD

**Issue by schnettker** [bolechen/nova-activitylog#1]
It seems that i missed some settings because nothing will be logged. I thought that your package log alle activities on all resources?!

**Comment by bolechen** [comment]
> Add `LogsActivity` trait to your model file will be fine.

Because backend we use the `spatie/laravel-activitylog` package, so your may enable the model event manual, see this link for detail:

https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events

**Comment by schnettker** [comment]
Thank you, works good
