### ISSUE TITLE
How do I restrict/set permissions for specific user roles?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [bolechen/nova-activitylog#13]
For example, how can some users not be able to edit and delete entries?

**Comment by oleksandr-roskovynskyi** [comment]
Also how to disable/hide the Create Activity Log button?

**Comment by bolechen** [comment]
Use Laravel policies to do this, ref link https://nova.laravel.com/docs/3.0/resources/authorization.html#policies

```
$ php artisan make:policy ActivityPolicy -m \\Spatie\\Activitylog\\Models\\Activity
```

**Comment by cerw** [comment]
Hmm this is not working for me in L9 file exist but nothing?
