### ISSUE TITLE
How to track changes through the model's static::creating() method?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [bolechen/nova-activitylog#16]
How to track changes through the model's static::creating() method?

The sample code from the model, logic execution and data change in the database is not tracked here:

```
public static function boot()
    {
        parent::boot();

        static::creating(function (Cost $cost) {
         // 
                User::update[
                //
                ];
        }
  }
```

**Comment by bolechen** [comment]
plz ref the `spatie/laravel-activitylog` doc at:
 https://spatie.be/docs/laravel-activitylog/v3/advanced-usage/logging-model-events
