### ISSUE TITLE
Can We get more details info

### ISSUE THREAD

**Issue by hendisantika** [bolechen/nova-activitylog#19]
Nice article.

Can We get more details information like Who do changes, email etc.

Those are really helpful.
Thanks

**Comment by bolechen** [comment]
use the  `Causer` field.

**Comment by hendisantika** [comment]
I want to get email address from the user who do this activity

**Comment by hendisantika** [comment]
Do You have full example for UI that on the README?

Thanks

**Comment by bolechen** [comment]
See README at the  `Customize` chapters:

1. Make a new activity model extends `Bolechen\NovaActivitylog\Resources\Activitylog`
1.  Change the resource in config/nova-activitylog.php to your custom nova resource.
1. Overwrite the `fields()` method add user mail use the displayUsing, nova docs link https://nova.laravel.com/docs/3.0/resources/fields.html#field-resolution-formatting

Hope helpful.

Also to see #5

**Comment by jirkacisar** [comment]
> 1. Make a new activity model extends `Bolechen\NovaActivitylog\Resources\Activitylog`

My model looks like:

```
<?php

namespace App;

class Aaa extends \Bolechen\NovaActivitylog\Resources\Activitylog
{

}
```

I've got this error message: ```BadMethodCallException - Method App\Aaa::saving does not exist.```

Did I miss something?

Thanks.
