### ISSUE TITLE
update for spatie/laravel-activitylog v4.0

### ISSUE THREAD

**Issue by felixsc** [bolechen/nova-activitylog#24]
Hi and thanks for this package @bolechen 

The [spatie/laravel-activitylog package is now on version 4](https://github.com/spatie/laravel-activitylog/releases/tag/4.0.0)  and the current requirement is "^3.9.1". 

Do you plan on updating it? From what I've seen it doesn't look nice changes are necessary.

**Comment by bolechen** [comment]
I'm on vacation. I'll update it as soon as possible.

陈伯乐
2021年7月15日 +0800 18:07 felixsc ***@***.***>，写道：

**Comment by MaxKorlaar** [comment]
Hi @bolechen, do you have any updates on this?

**Comment by bolechen** [comment]
https://github.com/bolechen/nova-activitylog/pull/25
