### ISSUE TITLE
How to add filters?

### ISSUE THREAD

**Issue by PaulLawton227** [bolechen/nova-activitylog#3]
I've made a local resource by extending your class, 
e.g. class ActivityLog extends \Bolechen\NovaActivitylog\Resources\Activitylog 
to try and override the filters function to add my own filter.

How do I get your nova tool to use my local ActivityLog (with filters) instead of the one in your package?

**Comment by bolechen** [comment]
You will try to change the `config/activitylog.php` file the `activity_model` filed to you local `ActivityLog` Model.

**Comment by bolechen** [comment]
Plz use the `0.1.4` version, I add the `Customize` chapter to the README file, hope this helpful.
