### ISSUE TITLE
Make activity log not editable

### ISSUE THREAD

**Issue by xndbogdan** [bolechen/nova-activitylog#32]
Hi. Can you make the activity log fields read only?
Or at least make a config file option to make them read only?

**Comment by bolechen** [comment]
Use Laravel policies to do this,see https://github.com/bolechen/nova-activitylog/issues/13

**Comment by TheAaronLawrence** [comment]
It seems that in newer versions of Laravel and or V4 on Nova.

You need to add a `Gate:policy()` for the activity log. you can add this to the `boot()` in `NovaServiceProvider`
example ```Gate::policy(Activity::class, ActivityPolicy::class);```
