### ISSUE TITLE
Nova Menu entry visible locally but not on staging

### ISSUE THREAD

**Issue by nea** [bolechen/nova-activitylog#35]
Ahoy there

I didn't find the same question hence me asking now: I am facing the issue that I can see the Actitiy Log menu in Nova 4 fine locally
![image](https://github.com/bolechen/nova-activitylog/assets/392035/25e21725-5ecd-47e2-abb7-75f8703b5488)

But as soon as I am uploading it (via Vapor), the menu entry is gone and trying to access it directly leads to a 404.

I do not see any configuration or value which could cause this here, but maybe I am missing something.

I just added it as Tools, as in the README, and locally all is fine. I just am lacking an idea why it won't show up on staging.

Does anybody has an idea or hint where to look for?

Thanks a lot

**Comment by henryavila** [comment]
Hi, this is tipically a problem with authorization. 
Take a look in th docs https://nova.laravel.com/docs/resources/authorization.html and make sure that you policy is granting access to model

**Comment by nea** [comment]
Thanks @henryavila , but I have no special Auth on the Staging server and have hardcoded a single user to use locally and on the Staging environment for the moment. No special Policies or Rules or anything different between both.

**Comment by henryavila** [comment]
I just founded that there's a bug

The following line on `https://github.com/bolechen/nova-activitylog/blob/master/src/NovaActivitylog.php#L38` should not exist.
![image](https://github.com/bolechen/nova-activitylog/assets/8429941/fe93c66d-f4df-429b-a578-f5f83058becc)

It lands to erro 404. Removing it fix the erro when accessing via custom Menu. Should solve your problem too

**Comment by henryavila** [comment]
I've creted the PR https://github.com/bolechen/nova-activitylog/pull/36 to solve this problem.
@bolechen, can you accept the PR?

**Comment by henryavila** [comment]
@nea, hope this helps you.
I always use [Custom Menu](https://nova.laravel.com/docs/customization/menus.html), perhaps this don't solves your problem. bu hope this point you to the way

**Comment by bolechen** [comment]
> 

ok,thx

**Comment by nea** [comment]
Damn guys, awesome ^^ Thanks big time both of you :)
