### ISSUE TITLE
Adding the Activity Log relation to the Nova User resource

### ISSUE THREAD

**Issue by graphem** [bolechen/nova-activitylog#39]
Thanks for the package.

Question, is there an easy way to add the Activity log relation ship to the Nova User resource based on the user model so that we can see all activity log of the user when going to the user details view. Thanks!

**Comment by AndreSchwarzer** [comment]
```php

<?php

// app/Nova/User.php

class User extends Resource
{
    public function fields(NovaRequest $request)
    {
        return [
            // ...
            MorphMany::make(__('Activity Log'), 'activities', \Bolechen\NovaActivitylog\Resources\Activitylog::class)->collapsedByDefault(),
        ];
    }
}
```

**Comment by AndreSchwarzer** [comment]
@graphem have you considered closing this issue since it seems to be solved, or do you need further assistance :)

**Comment by graphem** [comment]
For sure, thanks for your help!
