### ISSUE TITLE
Override Activitylog resource

### ISSUE THREAD

**Issue by 7krasov** [bolechen/nova-activitylog#5]
Hi! Thanks a lot for this nova package!
Could you please help me to override your Activitylog resource? Trying within NovaServiceProvider or my custom service provider - no success...
I would override fields method to output user name instead of id, but can't find the way. Maybe you could help...

Thanks!

**Comment by bolechen** [comment]
You my look the `Customize ` section in the `README` file, create your owner resource file extends the original like this and override the `fields` method:

```php
class Activity extends Activitylog
{
//...

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make('Description'),
            Text::make('Subject Id'),
            Text::make('Subject Type'),

            Text::make('Causer', 'causer_id')->displayUsing(function ($user_id) {
                return \App\User::find($user_id)->name;
            }),

            Text::make('Causer Ip', 'properties->ip')->onlyOnIndex(),
            Code::make('properties')->json(JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE),
            DateTime::make('created_at'),
        ];
    }

//...
?>
```

**Comment by 7krasov** [comment]
Got it! :-) I tried just to "rebind" a resource with the inherited, with the same name via Laravel DI instead of getting a new name and override it within config... 
Works as you said, thank you :+1:

**Comment by paul-muckypuddle** [comment]
I'm having a similar problem but I think I'm missing something:

- I've created a resource, `Customactivitylog`, in the `app/Nova` directory, that overrides `Activitylog` from your package
- But I'm not sure what config value to provide?

**Comment by paul-muckypuddle** [comment]
Sorry, for some reason Nova wasn't registering the new resource. For other folk, adding:

````
protected function resources()
{
    parent::resources();
    Nova::resources([
        \Yourcustomactivitylog::class
    ]);
}
````
to `NovaServiceProvider.php` then using the resource name `yourcustomactivitylogs` in the tool config will work
